### ISSUE TITLE
Features list.

### ISSUE THREAD

**Issue by dwright** [unnaturaldevelopment/fles#51]
A list of features provided by FLES will help new users decide if they want to adopt it.

**Comment by unnaturaldeveloper** [comment]
Thanks for opening this ticket @dwright!
Initially, I did create a [wiki](https://github.com/unnaturaldevelopment/fles/wiki) that I have not updated in a while.

I can add an enumerated list of active features to the repository readme and will update the wiki.
Would that satisfy this issue?

**Comment by dwright** [comment]
@unnaturaldeveloper I think that would go a long way in helping.   From a UX perspective, you would want to make that list as easy to find as possible.   Either include it in the top-level readme, or make sure that readme includes a link to it.

**Comment by unnaturaldeveloper** [comment]
@dwright I just updated the repository readme, as well as the [wiki](https://github.com/unnaturaldevelopment/fles/wiki) so that it's current with the features available in FLES.
