### ISSUE TITLE
Redirect click on avatar to full image in gallery

### ISSUE THREAD

**Issue by xzorby** [unnaturaldevelopment/fles#53]
First time user. Unfortunately "Redirect click on avatar to full image in gallery" does not seem to work. I don't get the expected behaviour shown in fles-redirect_to_full_avatar.gif; I just get redirected to the user's gallery page whether the option is checked or not. Is this a known issue? Other features seem to work (e.g. highlighting common kinks).

OS: Ubuntu 20.04.3 LTS
Browser: Firefox 93.0 (64 bit)
UserScript manager: TamperMonkey 4.13.6136
The problem persists with no other Firefox extensions running.

**Comment by unnaturaldeveloper** [comment]
This is definitely a bug after the latest site update of the responsive profiles.

I'm able to reproduce it and identified the issue.
