### ISSUE TITLE
Does not work with GreaseMonkey: can't access settings

### ISSUE THREAD

**Issue by xzorby** [unnaturaldevelopment/fles#54]
First time user. I've copied the .js file, but I can't get to the settings. The gear icon only appears on main user pages and when it does, it is not clickable. On hover it says "FLES Settings" but I can't get to those settings. The icon does not appear at all on gallery pages, picture pages, event pages, writings pages, group pages, or on the /inbox and /conversations/.. pages.

OS: Ubuntu 20.04.3 LTS
Browser: Firefox 93.0 (64 bit)
UserScript manager: GreaseMonkey 4.11
The problem persists with no other Firefox extensions running.

I've tried TamperMonkey on the same system instead, and it seems to work better (although I can't get [avatar click to full gallery](https://github.com/unnaturaldevelopment/fles/issues/53) to work).

**Comment by unnaturaldeveloper** [comment]
@xzorby Thanks for creating the issue.
Unfortunately, Greasemonkey doesn't support GM_addStyle in versions 4+ which FLES uses to define its stylesheet. I chose not to support it when I first wrote FLES as it wasn't being actively developed (it looks like the [last commit](https://github.com/greasemonkey/greasemonkey/branches) in the public repository was in January of this year). 

Personally, I use Tampermonkey and test with Violentmonkey as well.
